// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAOgfV4g-Z44w8tfXHACKnVY0931ZfWM',
    appId: '1:278470263970:web:9762c26c1db504a62683fb',
    messagingSenderId: '278470263970',
    projectId: 'chat-app-29922',
    authDomain: 'chat-app-29922.firebaseapp.com',
    storageBucket: 'chat-app-29922.appspot.com',
    measurementId: 'G-ZCYGPYJCQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXJw4cUwk1qKqgMghG0LHn9557BmVa8M',
    appId: '1:278470263970:android:8ddc3cd5b0a6dc592683fb',
    messagingSenderId: '278470263970',
    projectId: 'chat-app-29922',
    storageBucket: 'chat-app-29922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjePnoYU9BQYnbsg2zelRXDnev0KdtuPU',
    appId: '1:278470263970:ios:21cdb345c36d76072683fb',
    messagingSenderId: '278470263970',
    projectId: 'chat-app-29922',
    storageBucket: 'chat-app-29922.appspot.com',
    iosClientId: '278470263970-io6shet0792b8lfpkrf80sdk96s4183j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjePnoYU9BQYnbsg2zelRXDnev0KdtuPU',
    appId: '1:278470263970:ios:e28911180d9ea1b22683fb',
    messagingSenderId: '278470263970',
    projectId: 'chat-app-29922',
    storageBucket: 'chat-app-29922.appspot.com',
    iosClientId: '278470263970-420rr18gbe8apka0nb7co5qpjf9489ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
